In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("../data/raw/issues.csv")

In [4]:
df.shape

(66691, 58)

In [5]:
df.head()

,id,started,ended,issue_num,issue_proj,issue_reporter,issue_assignee,issue_contr_count,issue_type,issue_priority,...,wf_cancelled,wfe_cancelled,wf_under_review,wfe_under_review,wf_approved,wfe_approved,wf_pending_deployment,wfe_pending_deployment,wf_total_time,processing_steps
0,11887.0,2016-01-06 08:23:43+00:00,2016-01-06 08:56:55+00:00,186.0,d1z0,4olg,NaN,1.0,Ticket,Medium,...,NaN,0,NaN,0,NaN,0,NaN,0,1992.0,2
1,11890.0,2016-01-11 10:06:19+00:00,2016-01-12 12:30:23+00:00,190.0,d1z0,4olg,NaN,1.0,Ticket,Medium,...,NaN,0,NaN,0,NaN,0,NaN,0,95044.0,2
2,11904.0,2016-01-21 07:28:20+00:00,2016-01-26 08:21:47+00:00,198.0,d1z0,4ohk,4ohk,1.0,Ticket,Medium,...,NaN,0,NaN,0,NaN,0,NaN,0,435207.0,2
3,11907.0,2016-01-26 07:44:54+00:00,2016-01-26 07:45:48+00:00,209.0,d1z0,4olg,NaN,1.0,Vacation,Medium,...,NaN,0,NaN,0,NaN,0,NaN,0,54.0,2
4,11912.0,2016-02-01 13:45:47+00:00,2016-02-07 06:21:42+00:00,217.0,d1z0,4ohk,4ohk,1.0,Story,Medium,...,NaN,0,NaN,0,NaN,0,NaN,0,491755.0,2

In [6]:
df.columns.tolist()

['id',
 'started',
 'ended',
 'issue_num',
 'issue_proj',
 'issue_reporter',
 'issue_assignee',
 'issue_contr_count',
 'issue_type',
 'issue_priority',
 'issue_created',
 'issue_resolution_date',
 'issue_resolution',
 'issue_status',
 'issue_comments_count',
 'last_change_date',
 'wf_in_review',
 'wfe_in_review',
 'wf_deployment',
 'wfe_deployment',
 'wf_resolved',
 'wfe_resolved',
 'wf_open',
 'wfe_open',
 'wf_monitoring',
 'wfe_monitoring',
 'wf_done',
 'wfe_done',
 'wf_pending_customer_approval',
 'wfe_pending_customer_approval',
 'wf_rejected',
 'wfe_rejected',
 'wf_testing_monitoring',
 'wfe_testing_monitoring',
 'wf_in_progress',
 'wfe_in_progress',
 'wf_reopened',
 'wfe_reopened',
 'wf_to_do',
 'wfe_to_do',
 'wf_validation',
 'wfe_validation',
 'wf_resolved_under_monitoring',
 'wfe_resolved_under_monitoring',
 'wf_closed',
 'wfe_closed',
 'wf_waiting',
 'wfe_waiting',
 'wf_cancelled',
 'wfe_cancelled',
 'wf_under_review',
 'wfe_under_review',
 'wf_approved',
 'wfe_approved',
 'wf_pending_deployment',
 'wfe_pending_deployment',
 'wf_total_time',
 'processing_steps']

In [9]:
selected_columns = [
    "id",
    "issue_num",
    "issue_proj",
    "issue_reporter",
    "issue_assignee",
    "issue_contr_count",
    "issue_type",
    "issue_priority",
    "issue_created",
    "issue_resolution_date",
    "issue_resolution",
    "issue_status",
    "issue_comments_count",
    "last_change_date",
    "wf_total_time",
    "processing_steps"
]

df_analysis = df[selected_columns].copy()

In [10]:
df_analysis.head()

,id,issue_num,issue_proj,issue_reporter,issue_assignee,issue_contr_count,issue_type,issue_priority,issue_created,issue_resolution_date,issue_resolution,issue_status,issue_comments_count,last_change_date,wf_total_time,processing_steps
0,11887.0,186.0,d1z0,4olg,NaN,1.0,Ticket,Medium,2016-01-06 08:23:43+00:00,2016-01-06 08:56:55+00:00,Done,done,1,2016-04-02 12:20:21+00:00,1992.0,2
1,11890.0,190.0,d1z0,4olg,NaN,1.0,Ticket,Medium,2016-01-11 10:06:19+00:00,2016-01-12 12:30:23+00:00,Done,done,0,2016-04-02 12:20:21+00:00,95044.0,2
2,11904.0,198.0,d1z0,4ohk,4ohk,1.0,Ticket,Medium,2016-01-21 07:28:20+00:00,2016-01-26 08:21:47+00:00,Done,done,0,2016-04-02 12:20:21+00:00,435207.0,2
3,11907.0,209.0,d1z0,4olg,NaN,1.0,Vacation,Medium,2016-01-26 07:44:54+00:00,2016-01-26 07:45:48+00:00,Done,done,1,2016-04-02 12:20:21+00:00,54.0,2
4,11912.0,217.0,d1z0,4ohk,4ohk,1.0,Story,Medium,2016-02-01 13:45:47+00:00,2016-02-07 06:21:42+00:00,Done,done,5,2016-04-02 12:20:21+00:00,491755.0,2

In [11]:
df_analysis.shape

(66691, 16)

In [12]:
df_analysis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66691 entries, 0 to 66690
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     66691 non-null  float64
 1   issue_num              66691 non-null  float64
 2   issue_proj             66691 non-null  object
 3   issue_reporter         66691 non-null  object
 4   issue_assignee         35644 non-null  object
 5   issue_contr_count      66691 non-null  float64
 6   issue_type             66691 non-null  object
 7   issue_priority         66691 non-null  object
 8   issue_created          66691 non-null  object
 9   issue_resolution_date  65838 non-null  object
 10  issue_resolution       65838 non-null  object
 11  issue_status           66691 non-null  object
 12  issue_comments_count   66691 non-null  int64
 13  last_change_date       66690 non-null  object
 14  wf_total_time          66691 non-null  float64
 15  processing_steps       66691 non-null  int64
dtypes: float64(4), int64(2), object(10)
memory usage: 8.1+ MB

In [13]:
df_analysis.isnull().sum().sort_values(ascending=False)

issue_assignee           31047
issue_resolution_date      853
issue_resolution           853
last_change_date             1
id                           0
issue_num                    0
issue_proj                   0
issue_reporter               0
issue_contr_count            0
issue_type                   0
issue_priority               0
issue_created                0
issue_status                 0
issue_comments_count         0
wf_total_time                0
processing_steps             0
dtype: int64

In [14]:
df_analysis.dtypes

id                       float64
issue_num                float64
issue_proj                object
issue_reporter            object
issue_assignee            object
issue_contr_count        float64
issue_type                object
issue_priority            object
issue_created             object
issue_resolution_date     object
issue_resolution          object
issue_status              object
issue_comments_count       int64
last_change_date          object
wf_total_time            float64
processing_steps           int64
dtype: object

In [15]:
df_analysis.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
id,66691.0,NaN,NaN,NaN,10119669.553568,15316756.55859,10616.0,28953.5,1001949.0,19092500.0,47806000.0
issue_num,66691.0,NaN,NaN,NaN,951.301255,1030.594169,1.0,101.0,322.0,2109.0,3543.0
issue_proj,66691,358,t.n2,2213,NaN,NaN,NaN,NaN,NaN,NaN,NaN
issue_reporter,66691,1114,4rqs,1019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
issue_assignee,35644,381,4pps,1479,NaN,NaN,NaN,NaN,NaN,NaN,NaN
issue_contr_count,66691.0,NaN,NaN,NaN,1.220405,0.533835,1.0,1.0,1.0,1.0,10.0
issue_type,66691,15,Ticket,45275,NaN,NaN,NaN,NaN,NaN,NaN,NaN
issue_priority,66691,7,unknown,33965,NaN,NaN,NaN,NaN,NaN,NaN,NaN
issue_created,66691,66281,2023-03-05 19:35:00+00:00,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
issue_resolution_date,65838,64938,2017-11-19 07:41:30+00:00,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
issue_resolution,65838,4,Done,62034,NaN,NaN,NaN,NaN,NaN,NaN,NaN
issue_status,66691,15,closed,56344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
issue_comments_count,66691.0,NaN,NaN,NaN,8.641796,13.785747,0.0,3.0,5.0,10.0,685.0
last_change_date,66690,59651,2016-04-02 13:18:52+00:00,195,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wf_total_time,66691.0,NaN,NaN,NaN,65856465.205007,99715344.055487,0.0,440845.3655,2961971.0,129318977.035,357193929.875
processing_steps,66691.0,NaN,NaN,NaN,3.214542,2.855747,0.0,1.0,3.0,4.0,93.0

In [16]:
for col in df_analysis.columns:
    print("\n" + "=" * 60)
    print(col)
    print("=" * 60)
    print(df_analysis[col].value_counts(dropna=False).head(15))

============================================================
id
============================================================
id
11887.0    1
36118.0    1
28977.0    1
28995.0    1
35366.0    1
34882.0    1
35285.0    1
35219.0    1
35655.0    1
29023.0    1
29027.0    1
34799.0    1
34885.0    1
35440.0    1
39836.0    1
Name: count, dtype: int64

============================================================
issue_num
============================================================
issue_num
2.0     269
3.0     258
4.0     255
6.0     251
5.0     249
8.0     246
7.0     243
11.0    232
1.0     231
9.0     231
10.0    231
13.0    225
12.0    222
14.0    220
15.0    217
Name: count, dtype: int64

============================================================
issue_proj
============================================================
issue_proj
t.n2          2213
C06hg2xcu     1994
C13ggb_0      1522
dx8a          1474
C06ggzcz0     1289
C06ggn039     1251
C01ggx0z2      979
C01ggz-3       942
db6            932
C13gg20        864
C06gg1z0       809
C13ggbx0       785
C12hgx18a      723
C06ggtz0       679
C12ggzcz0u     661
Name: count, dtype: int64

============================================================
issue_reporter
============================================================
issue_reporter
4rqs          1019
4opp           867
4hlg           820
bzyb_0ygh      800
t.yn039ygo     690
4gor           618
t.y1z0ygh      573
bzyb_0ygo      573
t.yt_9ygh      570
z8yz-3ygp      545
t.y2xcuyhp     526
u6yx0uygs      515
4qio           512
4hho           503
4ogg           495
Name: count, dtype: int64

============================================================
issue_assignee
============================================================
issue_assignee
NaN     31047
4pps     1479
4ikk     1262
4ihs     1035
4osr      970
4prg      888
4pgp      878
4hpp      873
4oqq      841
4pqq      711
4qsk      690
4psk      675
4qiq      656
4qqr      618
4qoh      617
Name: count, dtype: int64

============================================================
issue_contr_count
============================================================
issue_contr_count
1.0     55044
2.0      9149
3.0      2054
4.0       368
5.0        56
6.0        12
7.0         4
8.0         3
10.0        1
Name: count, dtype: int64

============================================================
issue_type
============================================================
issue_type
Ticket            45275
Service            5300
Subtask            4746
Story              4538
HD Service         1686
Task               1540
Vacation            856
Project             842
Sub-task            544
Epic                403
Deployment          350
Retrospective       241
Sprint Summary      208
Assistance          109
Bug                  53
Name: count, dtype: int64

============================================================
issue_priority
============================================================
issue_priority
unknown    33965
Medium     24788
High        4554
Highest     2084
Blocker      656
Low          560
Lowest        84
Name: count, dtype: int64

============================================================
issue_created
============================================================
issue_created
2023-03-05 19:35:00+00:00    42
2023-03-05 19:34:12+00:00    15
2017-04-23 08:56:21+00:00     7
2016-10-15 18:38:16+00:00     7
2017-04-23 08:56:16+00:00     7
2017-04-23 08:56:17+00:00     7
2016-10-15 10:38:59+00:00     7
2016-10-15 10:32:50+00:00     6
2016-10-15 10:32:51+00:00     6
2016-10-15 10:47:58+00:00     6
2017-04-23 08:56:18+00:00     6
2016-10-15 10:51:18+00:00     6
2016-10-15 10:53:45+00:00     6
2016-12-07 12:40:37+00:00     6
2016-11-05 18:27:33+00:00     6
Name: count, dtype: int64

============================================================
issue_resolution_date
============================================================
issue_resolution_date
NaN                          853
2017-11-19 07:41:30+00:00     13
2017-11-19 07:41:31+00:00     12
2016-12-02 14:53:50+00:00     12
2017-09-17 11:43:26+00:00     11
2017-09-17 11:43:21+00:00     11
2017-11-19 07:41:29+00:00     11
2016-12-02 14:53:49+00:00     11
2017-09-17 11:49:13+00:00     11
2017-09-17 11:49:28+00:00     11
2017-09-17 11:49:27+00:00     11
2017-09-17 11:43:06+00:00     11
2018-01-24 05:32:42+00:00     11
2017-09-17 11:49:21+00:00     11
2017-09-17 11:49:12+00:00     11
Name: count, dtype: int64

============================================================
issue_resolution
============================================================
issue_resolution
Done                62034
Won't Do             2991
NaN                   853
Duplicate             661
Cannot Reproduce      152
Name: count, dtype: int64

============================================================
issue_status
============================================================
issue_status
closed                       56344
done                          9714
waiting                        218
open                            97
in_progress                     94
validation                      86
resolved                        59
pending_deployment              47
resolved_under_monitoring       18
under_review                     5
to_do                            3
approved                         2
in_review                        2
cancelled                        1
reopened                         1
Name: count, dtype: int64

============================================================
issue_comments_count
============================================================
issue_comments_count
4     6108
3     6098
5     5731
6     5516
2     5417
0     5114
1     4939
7     4508
8     3563
9     2701
10    2258
11    1782
12    1436
13    1255
14    1106
Name: count, dtype: int64

============================================================
last_change_date
============================================================
last_change_date
2016-04-02 13:18:52+00:00    195
2016-04-02 12:20:21+00:00    169
2016-04-02 12:28:39+00:00    157
2016-04-02 13:23:37+00:00    145
2016-04-02 12:36:50+00:00    138
2016-04-02 12:41:41+00:00    137
2016-04-02 12:13:35+00:00    135
2016-04-02 12:56:56+00:00    132
2016-04-02 13:00:18+00:00    131
2016-04-02 12:16:58+00:00    121
2016-04-02 11:59:23+00:00    110
2017-05-12 20:25:49+00:00    110
2017-05-12 20:26:49+00:00    102
2016-04-02 13:10:04+00:00    101
2017-05-12 20:25:23+00:00     94
Name: count, dtype: int64

============================================================
wf_total_time
============================================================
wf_total_time
0.0     78
14.0    15
18.0    14
13.0    13
49.0    11
15.0    10
23.0    10
75.0    10
17.0    10
34.0     9
26.0     9
21.0     9
54.0     9
16.0     9
11.0     9
Name: count, dtype: int64

============================================================
processing_steps
============================================================
processing_steps
1     26192
4     12196
3      7137
2      6199
5      5722
6      3289
7      1806
8      1270
9       766
10      564
11      364
12      244
13      200
14      137
15      117
Name: count, dtype: int64

In [17]:
df_clean = df_analysis.copy()

In [18]:
df_clean.shape

(66691, 16)

In [19]:
df_clean["id"].duplicated().sum()

np.int64(0)

In [20]:
df_clean["issue_num"].duplicated().sum()

np.int64(63149)

In [21]:
df_clean.duplicated().sum()

np.int64(0)

In [22]:
df_clean["id"] = df_clean["id"].astype("Int64")
df_clean["issue_num"] = df_clean["issue_num"].astype("Int64")
df_clean["issue_contr_count"] = df_clean["issue_contr_count"].astype("Int64")

In [23]:
df_clean[[
    "id",
    "issue_num",
    "issue_contr_count"
]].dtypes

id                   Int64
issue_num            Int64
issue_contr_count    Int64
dtype: object

In [24]:
date_columns = [
    "issue_created",
    "issue_resolution_date",
    "last_change_date"
]

for col in date_columns:
    df_clean[col] = pd.to_datetime(
        df_clean[col],
        errors="coerce",
        utc=True
    )

In [25]:
df_clean[date_columns].dtypes

issue_created            datetime64[ns, UTC]
issue_resolution_date    datetime64[ns, UTC]
last_change_date         datetime64[ns, UTC]
dtype: object

In [26]:
df_clean[date_columns].isnull().sum()

issue_created            16595
issue_resolution_date    37460
last_change_date         40720
dtype: int64

In [27]:
print("Earliest ticket:",
      df_clean["issue_created"].min())

print("Latest ticket:",
      df_clean["issue_created"].max())

Earliest ticket: 2007-04-15 08:12:11+00:00
Latest ticket: 2023-03-14 14:00:32+00:00

In [28]:
print("Earliest resolution:",
      df_clean["issue_resolution_date"].min())

print("Latest resolution:",
      df_clean["issue_resolution_date"].max())

Earliest resolution: 2013-01-07 09:45:42+00:00
Latest resolution: 2023-03-14 14:19:28+00:00

In [29]:
invalid_resolution_dates = (
    df_clean["issue_resolution_date"]
    < df_clean["issue_created"]
)

invalid_resolution_dates.sum()

np.int64(0)

In [30]:
df_clean["resolution_time_hours"] = (
    df_clean["issue_resolution_date"]
    - df_clean["issue_created"]
).dt.total_seconds() / 3600

In [31]:
df_clean["resolution_time_hours"].describe()

count    28496.000000
mean      1902.602571
std       4644.304998
min          0.000833
25%         48.747431
50%        266.468333
75%       1167.330625
max      91967.239444
Name: resolution_time_hours, dtype: float64

In [32]:
df_clean["wf_total_time_hours"] = (
    df_clean["wf_total_time"] / 3600
)

In [33]:
df_clean[
    [
        "resolution_time_hours",
        "wf_total_time_hours"
    ]
].describe()

       resolution_time_hours  wf_total_time_hours
count           28496.000000         66691.000000
mean             1902.602571         18293.462557
std              4644.304998         27698.706682
min                 0.000833             0.000000
25%                48.747431           122.457046
50%               266.468333           822.769722
75%              1167.330625         35921.938065
max             91967.239444         99220.536076

In [34]:
df_clean["time_difference_hours"] = (
    df_clean["resolution_time_hours"]
    - df_clean["wf_total_time_hours"]
)

In [35]:
df_clean["time_difference_hours"].describe()

count    28496.000000
mean       -69.070846
std       1700.549218
min     -46004.591111
25%         -0.001111
50%          0.000000
75%          0.000000
max      15864.730556
Name: time_difference_hours, dtype: float64

In [36]:
unresolved = df_clean[
    df_clean["issue_resolution_date"].isna()
]

unresolved["issue_status"].value_counts()

issue_status
closed                       33771
done                          3056
waiting                        218
open                            97
in_progress                     94
validation                      86
resolved                        59
pending_deployment              47
resolved_under_monitoring       18
under_review                     5
to_do                            3
approved                         2
in_review                        2
cancelled                        1
reopened                         1
Name: count, dtype: int64

In [37]:
unresolved["issue_resolution"].value_counts(dropna=False)

issue_resolution
Done                34550
Won't Do             1729
NaN                   853
Duplicate             264
Cannot Reproduce       64
Name: count, dtype: int64

In [39]:
df_clean["is_resolved"] = (
    df_clean["issue_resolution_date"].notna()
)
df_clean["is_resolved"].value_counts()

is_resolved
False    37460
True     29231
Name: count, dtype: int64

In [40]:
df_clean["resolution_status"] = np.where(
    df_clean["issue_resolution_date"].notna(),
    "Resolved",
    "Unresolved"
)
df_clean["resolution_status"].value_counts()

resolution_status
Unresolved    37460
Resolved      29231
Name: count, dtype: int64

In [42]:
df_clean["wf_total_time_hours"] = (
    df_clean["wf_total_time"] / 3600
)
df_clean["wf_total_time_days"] = (
    df_clean["wf_total_time"] / 86400
)

In [44]:
df_clean["created_year"] = (
    df_clean["issue_created"].dt.year
)
df_clean["created_month"] = (
    df_clean["issue_created"].dt.month
)
df_clean["created_month_name"] = (
    df_clean["issue_created"].dt.month_name()
)
df_clean["created_quarter"] = (
    "Q" + df_clean["issue_created"].dt.quarter.astype(str)
)
df_clean["created_weekday"] = (
    df_clean["issue_created"].dt.day_name()
)
df_clean["created_weekday"] = (
    df_clean["issue_created"].dt.day_name()
)

In [45]:
df_clean["created_date"] = (
    df_clean["issue_created"].dt.date
)

In [46]:
analysis_end_date = df_clean["last_change_date"].max()

print(analysis_end_date)
df_clean["ticket_age_days"] = (
    (
        df_clean["issue_resolution_date"].fillna(
            analysis_end_date
        )
        - df_clean["issue_created"]
    ).dt.total_seconds()
    / 86400
)

2023-03-14 14:19:32+00:00

In [47]:
df_clean["processing_steps"].describe()

count    66691.000000
mean         3.214542
std          2.855747
min          0.000000
25%          1.000000
50%          3.000000
75%          4.000000
max         93.000000
Name: processing_steps, dtype: float64

In [48]:
df_clean["workflow_complexity"] = pd.cut(
    df_clean["processing_steps"],
    bins=[0, 2, 5, 10, np.inf],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

In [49]:
df_clean["assignee_status"] = np.where(
    df_clean["issue_assignee"].isna(),
    "Unassigned",
    "Assigned"
)
df_clean["issue_assignee"] = (
    df_clean["issue_assignee"]
    .fillna("Unassigned")
)

In [50]:
df_clean["issue_type"].value_counts()

issue_type
Ticket            45275
Service            5300
Subtask            4746
Story              4538
HD Service         1686
Task               1540
Vacation            856
Project             842
Sub-task            544
Epic                403
Deployment          350
Retrospective       241
Sprint Summary      208
Assistance          109
Bug                  53
Name: count, dtype: int64

In [51]:
pd.crosstab(
    df_clean["issue_status"],
    df_clean["issue_resolution"],
    dropna=False
)

issue_resolution           Cannot Reproduce   Done  Duplicate  Won't Do  NaN
issue_status
approved                                  0      0          0         0    2
cancelled                                 0      0          0         0    1
closed                                  152  53358        660      1982  192
done                                      0   8676          1      1009   28
in_progress                               0      0          0         0   94
in_review                                 0      0          0         0    2
open                                      0      0          0         0   97
pending_deployment                        0      0          0         0   47
reopened                                  0      0          0         0    1
resolved                                  0      0          0         0   59
resolved_under_monitoring                 0      0          0         0   18
to_do                                     0      0          0         0    3
under_review                              0      0          0         0    5
validation                                0      0          0         0   86
waiting                                   0      0          0         0  218

In [52]:
pd.crosstab(
    df_clean["issue_resolution"].isna(),
    df_clean["issue_resolution_date"].isna()
)

issue_resolution_date  False  True
issue_resolution
False                  29231  36607
True                       0    853

In [53]:
resolved_values = [
    "Done",
    "Won't Do",
    "Duplicate",
    "Cannot Reproduce"
]

df_clean["resolution_based_status"] = np.where(
    df_clean["issue_resolution"].isin(resolved_values),
    "Resolved",
    "Unresolved"
)

pd.crosstab(
    df_clean["resolution_based_status"],
    df_clean["issue_status"]
)

issue_status,approved,cancelled,closed,done,in_progress,in_review,open,pending_deployment,reopened,resolved,resolved_under_monitoring,to_do,under_review,validation,waiting
resolution_based_status,,,,,,,,,,,,,,,
Resolved,0,0,56152,9686,0,0,0,0,0,0,0,0,0,0,0
Unresolved,2,1,192,28,94,2,97,47,1,59,18,3,5,86,218

In [54]:
df_clean.drop(
    columns=["time_difference_hours"],
    inplace=True
)

In [55]:
df_clean[
    [
        "resolution_time_hours",
        "wf_total_time_hours",
        "processing_steps"
    ]
].describe()

       resolution_time_hours  wf_total_time_hours  processing_steps
count           28496.000000         66691.000000      66691.000000
mean             1902.602571         18293.462557          3.214542
std              4644.304998         27698.706682          2.855747
min                 0.000833             0.000000          0.000000
25%                48.747431           122.457046          1.000000
50%               266.468333           822.769722          3.000000
75%              1167.330625         35921.938065          4.000000
max             91967.239444         99220.536076         93.000000

In [56]:
df_clean[
    [
        "issue_num",
        "issue_created",
        "issue_resolution_date",
        "resolution_time_hours",
        "wf_total_time_hours",
        "processing_steps"
    ]
].sort_values(
    "resolution_time_hours",
    ascending=False
).head(10)

,issue_num,issue_created,issue_resolution_date,resolution_time_hours,wf_total_time_hours,processing_steps
5844,733,2008-02-11 13:29:31+00:00,2018-08-09 12:43:53+00:00,91967.239444,91967.239445,1
37895,2012,2009-01-07 07:18:33+00:00,2018-08-08 07:12:07+00:00,83999.892778,83999.892779,4
4073,2012,2009-06-25 08:18:36+00:00,2018-08-14 15:57:57+00:00,80095.655833,80095.655834,1
5041,65,2010-01-31 12:22:49+00:00,2018-08-13 14:32:01+00:00,74786.153333,74786.153334,1
8891,4,2010-05-04 08:16:12+00:00,2018-08-14 15:42:05+00:00,72583.431389,72583.431389,1
33687,11,2010-06-17 11:28:47+00:00,2018-08-14 15:33:55+00:00,71524.085556,71524.085556,1
6081,2236,2011-10-05 10:53:45+00:00,2018-08-09 13:09:25+00:00,60002.261111,60002.261112,1
10705,65,2011-10-26 07:55:52+00:00,2018-08-14 16:10:30+00:00,59624.243889,59624.243889,1
38302,9,2012-07-12 04:56:47+00:00,2018-08-14 16:06:52+00:00,53387.168056,53387.168056,1
24070,366,2016-03-08 15:08:33+00:00,2021-10-07 05:42:36+00:00,48926.567500,48926.568333,1

In [57]:
df_clean.drop(
    columns=[
        "is_resolved",
        "resolution_status"
    ],
    inplace=True
)

In [58]:
df_clean[
    df_clean["issue_type"].isin(["Subtask", "Sub-task"])
]["issue_status"].value_counts()
df_clean[
    df_clean["issue_type"].isin(["Subtask", "Sub-task"])
]["issue_priority"].value_counts()

issue_priority
unknown    4604
Medium      637
High         33
Highest       7
Lowest        5
Low           3
Blocker       1
Name: count, dtype: int64

In [59]:
df_clean["priority_known"] = np.where(
    df_clean["issue_priority"].eq("unknown"),
    "Unknown",
    "Known"
)

In [61]:
df_clean["issue_assignee"].isna().mean() * 100
df_clean["assignee_status"] = np.where(
    df_clean["issue_assignee"].isna(),
    "Unassigned",
    "Assigned"
)

In [62]:
df_clean[
    [
        "issue_created",
        "issue_resolution_date",
        "last_change_date"
    ]
].head(20)

,issue_created,issue_resolution_date,last_change_date
0,2016-01-06 08:23:43+00:00,2016-01-06 08:56:55+00:00,2016-04-02 12:20:21+00:00
1,2016-01-11 10:06:19+00:00,2016-01-12 12:30:23+00:00,2016-04-02 12:20:21+00:00
2,2016-01-21 07:28:20+00:00,2016-01-26 08:21:47+00:00,2016-04-02 12:20:21+00:00
3,2016-01-26 07:44:54+00:00,2016-01-26 07:45:48+00:00,2016-04-02 12:20:21+00:00
4,2016-02-01 13:45:47+00:00,2016-02-07 06:21:42+00:00,2016-04-02 12:20:21+00:00
5,2016-02-02 08:14:46+00:00,2016-02-14 21:24:46+00:00,2016-04-02 12:20:21+00:00
6,2016-02-11 08:59:12+00:00,2016-02-14 10:55:18+00:00,2016-04-02 12:20:21+00:00
7,2016-02-11 12:53:42+00:00,2016-03-06 10:05:31+00:00,2016-04-02 12:20:21+00:00
8,2016-02-16 08:41:58+00:00,2016-02-22 07:02:01+00:00,2016-04-02 12:20:21+00:00
9,2016-02-22 08:20:40+00:00,2016-08-29 13:14:38+00:00,2016-08-29 13:14:38+00:00
10,2016-02-23 08:49:49+00:00,2016-02-23 12:32:00+00:00,2016-04-02 12:20:21+00:00
11,2016-02-25 07:35:31+00:00,2016-02-25 08:25:59+00:00,2016-04-02 12:20:21+00:00
12,2016-03-01 07:54:33+00:00,2016-03-15 07:44:51+00:00,2016-04-02 12:20:21+00:00
13,2016-03-03 15:09:03+00:00,2016-03-06 10:08:17+00:00,2016-04-02 12:20:21+00:00
14,2016-03-06 10:39:09+00:00,2016-03-13 14:34:49+00:00,2016-04-02 12:20:21+00:00
15,2016-03-07 15:54:31+00:00,2016-03-08 12:19:34+00:00,2016-04-02 12:20:21+00:00
16,2016-03-09 09:32:35+00:00,2016-03-15 07:45:31+00:00,2016-04-02 12:20:21+00:00
17,2016-03-09 11:39:44+00:00,2016-03-27 08:37:47+00:00,2016-04-02 12:20:21+00:00
18,2016-03-09 11:39:56+00:00,2016-03-23 14:45:37+00:00,2016-04-02 12:20:21+00:00
19,2016-03-15 08:03:16+00:00,2016-03-27 07:04:20+00:00,2016-04-02 12:20:21+00:00

In [64]:
(df_clean["last_change_date"] < df_clean["issue_created"]).sum()
df_clean["last_change_date"].min(), df_clean["last_change_date"].max()

(Timestamp('2016-04-02 11:59:22+0000', tz='UTC'),
 Timestamp('2023-03-14 14:19:32+0000', tz='UTC'))

In [65]:
pd.crosstab(
    df_clean["issue_status"],
    df_clean["issue_resolution"],
    dropna=False
)

issue_resolution           Cannot Reproduce   Done  Duplicate  Won't Do  NaN
issue_status
approved                                  0      0          0         0    2
cancelled                                 0      0          0         0    1
closed                                  152  53358        660      1982  192
done                                      0   8676          1      1009   28
in_progress                               0      0          0         0   94
in_review                                 0      0          0         0    2
open                                      0      0          0         0   97
pending_deployment                        0      0          0         0   47
reopened                                  0      0          0         0    1
resolved                                  0      0          0         0   59
resolved_under_monitoring                 0      0          0         0   18
to_do                                     0      0          0         0    3
under_review                              0      0          0         0    5
validation                                0      0          0         0   86
waiting                                   0      0          0         0  218

In [66]:
pd.crosstab(
    df_clean["issue_resolution"].isna(),
    df_clean["issue_resolution_date"].isna()
)

issue_resolution_date  False  True
issue_resolution
False                  29231  36607
True                       0    853

In [67]:
df_clean[
    df_clean["issue_type"].isin(["Subtask", "Sub-task"])
]["issue_status"].value_counts()

issue_status
closed    4790
done       500
Name: count, dtype: int64

In [68]:
df_clean["issue_assignee"].isna().mean() * 100

np.float64(0.0)

In [69]:
(df_clean["last_change_date"] < df_clean["issue_created"]).sum()

np.int64(0)

In [70]:
df_clean[
    [
        "resolution_time_hours",
        "wf_total_time_hours",
        "processing_steps"
    ]
].describe()

       resolution_time_hours  wf_total_time_hours  processing_steps
count           28496.000000         66691.000000      66691.000000
mean             1902.602571         18293.462557          3.214542
std              4644.304998         27698.706682          2.855747
min                 0.000833             0.000000          0.000000
25%                48.747431           122.457046          1.000000
50%               266.468333           822.769722          3.000000
75%              1167.330625         35921.938065          4.000000
max             91967.239444         99220.536076         93.000000

In [71]:
df_clean.drop(
    columns=[
        "is_resolved",
        "resolution_status",
        "time_difference_hours"
    ],
    errors="ignore",
    inplace=True
)

In [73]:
df_clean["is_resolved"] = (
    df_clean["issue_resolution_date"].notna()
)
df_clean["is_resolved"].value_counts()

is_resolved
False    37460
True     29231
Name: count, dtype: int64

In [74]:
df_clean["resolution_status"] = np.where(
    df_clean["is_resolved"],
    "Resolved",
    "Unresolved"
)
df_clean["resolution_status"].value_counts()

resolution_status
Unresolved    37460
Resolved      29231
Name: count, dtype: int64

In [76]:
df_clean["issue_type"] = (
    df_clean["issue_type"]
    .replace({
        "Sub-task": "Subtask"
    })
)
df_clean["issue_type"].value_counts()

issue_type
Ticket            45275
Service            5300
Subtask            5290
Story              4538
HD Service         1686
Task               1540
Vacation            856
Project             842
Epic                403
Deployment          350
Retrospective       241
Sprint Summary      208
Assistance          109
Bug                  53
Name: count, dtype: int64

In [77]:
df_clean["assignee_status"] = np.where(
    df_clean["issue_assignee"].isna(),
    "Unassigned",
    "Assigned"
)
df_clean["issue_assignee"] = (
    df_clean["issue_assignee"]
    .fillna("Unassigned")
)
df_clean["assignee_status"].value_counts()

assignee_status
Assigned    66691
Name: count, dtype: int64

In [78]:
df_clean["priority_status"] = np.where(
    df_clean["issue_priority"].eq("unknown"),
    "Unknown",
    "Known"
)
df_clean["priority_status"].value_counts()

priority_status
Unknown    33965
Known      32726
Name: count, dtype: int64

In [79]:
df_clean["resolution_time_hours"] = np.where(
    df_clean["is_resolved"],
    (
        df_clean["issue_resolution_date"]
        - df_clean["issue_created"]
    ).dt.total_seconds() / 3600,
    np.nan
)

In [80]:
df_clean[
    [
        "issue_created",
        "issue_resolution_date",
        "is_resolved",
        "resolution_time_hours"
    ]
].head(10)

,issue_created,issue_resolution_date,is_resolved,resolution_time_hours
0,2016-01-06 08:23:43+00:00,2016-01-06 08:56:55+00:00,True,0.553333
1,2016-01-11 10:06:19+00:00,2016-01-12 12:30:23+00:00,True,26.401111
2,2016-01-21 07:28:20+00:00,2016-01-26 08:21:47+00:00,True,120.890833
3,2016-01-26 07:44:54+00:00,2016-01-26 07:45:48+00:00,True,0.015000
4,2016-02-01 13:45:47+00:00,2016-02-07 06:21:42+00:00,True,136.598611
5,2016-02-02 08:14:46+00:00,2016-02-14 21:24:46+00:00,True,301.166667
6,2016-02-11 08:59:12+00:00,2016-02-14 10:55:18+00:00,True,73.935000
7,2016-02-11 12:53:42+00:00,2016-03-06 10:05:31+00:00,True,573.196944
8,2016-02-16 08:41:58+00:00,2016-02-22 07:02:01+00:00,True,142.334167
9,2016-02-22 08:20:40+00:00,2016-08-29 13:14:38+00:00,True,4540.899444

In [81]:
df_clean["workflow_time_hours"] = (
    df_clean["wf_total_time"] / 3600
)
df_clean["workflow_time_hours"] = (
    df_clean["wf_total_time"] / 3600
)

In [82]:
df_clean["workflow_complexity"] = pd.cut(
    df_clean["processing_steps"],
    bins=[-1, 2, 5, 10, np.inf],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

In [84]:
df_clean["workflow_complexity"].value_counts(
    sort=False
)

workflow_complexity
Low          32469
Medium       25055
High          7695
Very High     1472
Name: count, dtype: int64

In [85]:
df_clean["created_date"] = (
    df_clean["issue_created"].dt.date
)

df_clean["created_year"] = (
    df_clean["issue_created"].dt.year
)

df_clean["created_month"] = (
    df_clean["issue_created"].dt.month
)

df_clean["created_month_name"] = (
    df_clean["issue_created"].dt.month_name()
)

df_clean["created_quarter"] = (
    "Q" +
    df_clean["issue_created"]
    .dt.quarter
    .astype(str)
)

df_clean["created_weekday"] = (
    df_clean["issue_created"].dt.day_name()
)

df_clean["created_hour"] = (
    df_clean["issue_created"].dt.hour
)

In [86]:
df_clean["created_year_month"] = (
    df_clean["issue_created"]
    .dt.to_period("M")
    .astype(str)
)

/var/folders/z6/hfvywhys255bg6hylbh24t880000gn/T/ipykernel_50224/601749211.py:3: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  .dt.to_period("M")

In [87]:
df_clean["ticket_end_date"] = (
    df_clean["issue_resolution_date"]
    .fillna(analysis_end_date)
)
df_clean["ticket_age_days"] = (
    (
        df_clean["ticket_end_date"]
        - df_clean["issue_created"]
    ).dt.total_seconds()
    / 86400
)

In [88]:
(df_clean["ticket_age_days"] < 0).sum()

np.int64(0)

In [89]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66691 entries, 0 to 66690
Data columns (total 37 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       66691 non-null  Int64
 1   issue_num                66691 non-null  Int64
 2   issue_proj               66691 non-null  object
 3   issue_reporter           66691 non-null  object
 4   issue_assignee           66691 non-null  object
 5   issue_contr_count        66691 non-null  Int64
 6   issue_type               66691 non-null  object
 7   issue_priority           66691 non-null  object
 8   issue_created            50096 non-null  datetime64[ns, UTC]
 9   issue_resolution_date    29231 non-null  datetime64[ns, UTC]
 10  issue_resolution         65838 non-null  object
 11  issue_status             66691 non-null  object
 12  issue_comments_count     66691 non-null  int64
 13  last_change_date         25971 non-null  datetime64[ns, UTC]
 14  wf_total_time            66691 non-null  float64
 15  processing_steps         66691 non-null  int64
 16  resolution_time_hours    28496 non-null  float64
 17  wf_total_time_hours      66691 non-null  float64
 18  wf_total_time_days       66691 non-null  float64
 19  created_year             50096 non-null  float64
 20  created_month            50096 non-null  float64
 21  created_month_name       50096 non-null  object
 22  created_quarter          66691 non-null  object
 23  created_weekday          50096 non-null  object
 24  created_date             50096 non-null  object
 25  ticket_age_days          50096 non-null  float64
 26  workflow_complexity      66691 non-null  category
 27  assignee_status          66691 non-null  object
 28  resolution_based_status  66691 non-null  object
 29  priority_known           66691 non-null  object
 30  is_resolved              66691 non-null  bool
 31  resolution_status        66691 non-null  object
 32  priority_status          66691 non-null  object
 33  workflow_time_hours      66691 non-null  float64
 34  created_hour             50096 non-null  float64
 35  created_year_month       66691 non-null  object
 36  ticket_end_date          66691 non-null  datetime64[ns, UTC]
dtypes: Int64(3), bool(1), category(1), datetime64[ns, UTC](4), float64(9), int64(2), object(17)
memory usage: 18.1+ MB

In [90]:
df_clean["assignee_status"] = np.where(
    df_clean["issue_assignee"].eq("Unassigned"),
    "Unassigned",
    "Assigned"
)
df_clean["assignee_status"].value_counts()

assignee_status
Assigned      35644
Unassigned    31047
Name: count, dtype: int64

In [91]:
df_clean["comment_activity"] = pd.cut(
    df_clean["issue_comments_count"],
    bins=[-1, 0, 3, 10, np.inf],
    labels=[
        "No Comments",
        "Low",
        "Medium",
        "High"
    ]
)
df_clean["comment_activity"].value_counts(
    sort=False
)

comment_activity
No Comments     5114
Low            16454
Medium         30385
High           14738
Name: count, dtype: int64

In [92]:
df_clean["collaboration_level"] = pd.cut(
    df_clean["issue_contr_count"],
    bins=[0, 1, 2, 3, np.inf],
    labels=[
        "Single Contributor",
        "2 Contributors",
        "3 Contributors",
        "4+ Contributors"
    ]
)
df_clean["collaboration_level"].value_counts(
    sort=False
)

collaboration_level
Single Contributor    55044
2 Contributors         9149
3 Contributors         2054
4+ Contributors         444
Name: count, dtype: int64

In [93]:
monthly_tickets = (
    df_clean
    .groupby("created_year_month")
    .size()
    .reset_index(name="ticket_count")
)

monthly_tickets.head(20)

   created_year_month  ticket_count
0             2007-04            39
1             2007-05            54
2             2007-06            33
3             2007-07            70
4             2007-08            55
5             2007-09            42
6             2007-10            45
7             2007-11            61
8             2007-12            58
9             2008-01            52
10            2008-02            58
11            2008-03           129
12            2008-04           140
13            2008-05            77
14            2008-06           103
15            2008-07           126
16            2008-08            86
17            2008-09            68
18            2008-10            97
19            2008-11            98

In [94]:
yearly_tickets = (
    df_clean
    .groupby("created_year")
    .size()
    .reset_index(name="ticket_count")
)

yearly_tickets["yoy_growth_pct"] = (
    yearly_tickets["ticket_count"].pct_change() * 100
)

yearly_tickets

    created_year  ticket_count  yoy_growth_pct
0         2007.0           457             NaN
1         2008.0          1103      141.356674
2         2009.0          2157       95.557570
3         2010.0          3133       45.248030
4         2011.0          2966       -5.330354
5         2012.0          3071        3.540121
6         2013.0          2442      -20.481928
7         2014.0          2845       16.502867
8         2015.0          5543       94.833040
9         2016.0          7053       27.241566
10        2017.0          5524      -21.678718
11        2018.0          1212      -78.059377
12        2019.0             2      -99.834983
13        2020.0             7      250.000000
14        2021.0          4284    61100.000000
15        2022.0          6542       52.707750
16        2023.0          1755      -73.173341

In [95]:
df_clean["issue_type"].value_counts()

issue_type
Ticket            45275
Service            5300
Subtask            5290
Story              4538
HD Service         1686
Task               1540
Vacation            856
Project             842
Epic                403
Deployment          350
Retrospective       241
Sprint Summary      208
Assistance          109
Bug                  53
Name: count, dtype: int64

In [97]:
df_clean["issue_proj"].value_counts().head(15)

issue_proj
t.n2          2213
C06hg2xcu     1994
C13ggb_0      1522
dx8a          1474
C06ggzcz0     1289
C06ggn039     1251
C01ggx0z2      979
C01ggz-3       942
db6            932
C13gg20        864
C06gg1z0       809
C13ggbx0       785
C12hgx18a      723
C06ggtz0       679
C12ggzcz0u     661
Name: count, dtype: int64

In [98]:
df_clean[
    df_clean["is_resolved"]
]["resolution_time_hours"].describe()

count    28496.000000
mean      1902.602571
std       4644.304998
min          0.000833
25%         48.747431
50%        266.468333
75%       1167.330625
max      91967.239444
Name: resolution_time_hours, dtype: float64

In [99]:
resolution_by_priority = (
    df_clean[df_clean["is_resolved"]]
    .groupby("issue_priority")
    ["resolution_time_hours"]
    .agg(
        ticket_count="count",
        median_hours="median",
        average_hours="mean"
    )
    .reset_index()
)

resolution_by_priority.sort_values("median_hours")

  issue_priority  ticket_count  median_hours  average_hours
2        Highest          1845     76.930833     365.288089
0        Blocker           618     90.549861     747.077684
1           High          3973    115.762222     510.344604
4         Lowest            45    167.348889     645.777975
3            Low           406    188.265417     919.706026
5         Medium         11623    222.244444    1305.397466
6        unknown          9986    728.086389    3552.795696

In [100]:
workflow_resolution = (
    df_clean[df_clean["is_resolved"]]
    .groupby("workflow_complexity")["resolution_time_hours"]
    .agg(
        ticket_count="count",
        median_hours="median",
        mean_hours="mean"
    )
    .reset_index()
)

workflow_resolution.sort_values("median_hours")

/var/folders/z6/hfvywhys255bg6hylbh24t880000gn/T/ipykernel_50224/3420384836.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("workflow_complexity")["resolution_time_hours"]

  workflow_complexity  ticket_count  median_hours   mean_hours
1              Medium         13257    166.916667   770.632453
0                 Low         11667    379.099444  3404.237296
2                High          3197    506.978611  1104.143650
3           Very High           375   1342.231389  2008.279071

In [102]:
df_clean.columns.tolist()

['id',
 'issue_num',
 'issue_proj',
 'issue_reporter',
 'issue_assignee',
 'issue_contr_count',
 'issue_type',
 'issue_priority',
 'issue_created',
 'issue_resolution_date',
 'issue_resolution',
 'issue_status',
 'issue_comments_count',
 'last_change_date',
 'wf_total_time',
 'processing_steps',
 'resolution_time_hours',
 'wf_total_time_hours',
 'wf_total_time_days',
 'created_year',
 'created_month',
 'created_month_name',
 'created_quarter',
 'created_weekday',
 'created_date',
 'ticket_age_days',
 'workflow_complexity',
 'assignee_status',
 'resolution_based_status',
 'priority_known',
 'is_resolved',
 'resolution_status',
 'priority_status',
 'workflow_time_hours',
 'created_hour',
 'created_year_month',
 'ticket_end_date',
 'comment_activity',
 'collaboration_level']

In [103]:
df_clean.to_csv("../data/processed/helpdesk_cleaned.csv", index=False)

In [104]:
df_clean[df_clean["is_resolved"]].groupby(
    "workflow_complexity"
)["resolution_time_hours"].agg(
    ["count", "median", "mean"]
)

/var/folders/z6/hfvywhys255bg6hylbh24t880000gn/T/ipykernel_50224/873042918.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean[df_clean["is_resolved"]].groupby(

                     count       median         mean
workflow_complexity
Low                  11667   379.099444  3404.237296
Medium               13257   166.916667   770.632453
High                  3197   506.978611  1104.143650
Very High              375  1342.231389  2008.279071

In [105]:
df_clean[df_clean["is_resolved"]].groupby(
    "assignee_status"
)["resolution_time_hours"].agg(
    ["count", "median", "mean"]
)

                 count      median         mean
assignee_status
Assigned         19414  187.786528   700.895352
Unassigned        9082  837.249861  4471.413841

In [106]:
pd.crosstab(
    df_clean["issue_type"],
    df_clean["assignee_status"],
    normalize="index"
).round(3) * 100

assignee_status  Assigned  Unassigned
issue_type
Assistance           43.1        56.9
Bug                  26.4        73.6
Deployment           79.7        20.3
Epic                  6.0        94.0
HD Service           85.3        14.7
Project              74.3        25.7
Retrospective         6.2        93.8
Service              97.2         2.8
Sprint Summary       23.1        76.9
Story                30.8        69.2
Subtask               3.9        96.1
Task                 76.4        23.6
Ticket               55.3        44.7
Vacation             22.0        78.0

Data Preparation for Tableu

In [107]:
df_clean.columns.tolist()

['id',
 'issue_num',
 'issue_proj',
 'issue_reporter',
 'issue_assignee',
 'issue_contr_count',
 'issue_type',
 'issue_priority',
 'issue_created',
 'issue_resolution_date',
 'issue_resolution',
 'issue_status',
 'issue_comments_count',
 'last_change_date',
 'wf_total_time',
 'processing_steps',
 'resolution_time_hours',
 'wf_total_time_hours',
 'wf_total_time_days',
 'created_year',
 'created_month',
 'created_month_name',
 'created_quarter',
 'created_weekday',
 'created_date',
 'ticket_age_days',
 'workflow_complexity',
 'assignee_status',
 'resolution_based_status',
 'priority_known',
 'is_resolved',
 'resolution_status',
 'priority_status',
 'workflow_time_hours',
 'created_hour',
 'created_year_month',
 'ticket_end_date',
 'comment_activity',
 'collaboration_level']

In [108]:
df_clean.to_csv("helpdesk_clean.csv", index=False)